name: CRON Update Job

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
  
      - name: Check out source code
        uses: actions/checkout@v1
        
      - name: build the program
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: go build -o NotiGoCMS

      - name: Make dependency update script executable
        run: chmod +x ./update_notigocms.sh

      - name: Update Dependencies
        env:
          GITHUB_TOKEN_OVERRIDE: ${{ secrets.GH_TOKEN_OVERRIDE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: ./update_notigocms.sh
     
      - name: Make script executable
        run: chmod +x ./setup_env.sh

      - name: Update from notion
        env:
          GITHUB_TOKEN_OVERRIDE: ${{ secrets.GH_TOKEN_OVERRIDE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: ./setup_env.sh
